FROM virb3/wgcf:2.2 AS builder

FROM alpine:3


RUN apk update -f \
  && apk --no-cache add -f \
  curl ca-certificates \
  iproute2 net-tools iptables \
  wireguard-tools openresolv \
  && rm -rf /var/cache/apk/*
  
  
COPY --from=builder "/wgcf" "/usr/local/bin/wgcf"
RUN mkdir -p /wgcf

WORKDIR /wgcf

VOLUME /wgcf


COPY entry.sh /entry.sh
RUN chmod +x /entry.sh

ENTRYPOINT ["/entry.sh"]


